export const AV_STATE = {
    IDLE: 'IDLE',
    READY: 'READY',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
};


export const AV_ERROR  = {
    PLAYER_ERROR_NONE: "PLAYER_ERROR_NONE",
    PLAYER_ERROR_INVALID_PARAMETER: "PLAYER_ERROR_INVALID_PARAMETER",
    PLAYER_ERROR_NO_SUCH_FILE: "PLAYER_ERROR_NO_SUCH_FILE",
    PLAYER_ERROR_INVALID_OPERATION: "PLAYER_ERROR_INVALID_OPERATION",
    PLAYER_ERROR_SEEK_FAILED: "PLAYER_ERROR_SEEK_FAILED",
    PLAYER_ERROR_INVALID_STATE: "PLAYER_ERROR_INVALID_STATE",
    PLAYER_ERROR_NOT_SUPPORTED_FILE: "PLAYER_ERROR_NOT_SUPPORTED_FILE",
    PLAYER_ERROR_INVALID_URI: "PLAYER_ERROR_INVALID_URI",
    PLAYER_ERROR_CONNECTION_FAILED: "PLAYER_ERROR_CONNECTION_FAILED",
    PLAYER_ERROR_GENEREIC: "PLAYER_ERROR_GENEREIC"
  };

  